export const servicesData =  {
    categories: ['All', 'Waterbottle', 'Ornaments', 'Keyring','Packaging'],
    services: [
        { id: 1, image: '/assets/img/Portfolio/Portfolio image-1.jpg', title: 'Unicorn', category: 'Waterbottle', description: 'A description of our service...'},
        { id: 2, image: '/assets/img/Portfolio/Portfolio image-2.jpg', title: 'Smiley Face', category: 'Waterbottle', description: 'A description of our service...'},
        { id: 3, image: '/assets/img/Portfolio/Portfolio image-3.jpg', title: 'Rainbow', category: 'Waterbottle', description: 'A description of our service...'},
        { id: 4, image: '/assets/img/Portfolio/Portfolio image-4.jpg', title: 'Rainbow', category: 'Waterbottle', description: 'A description of our service...'},
        { id: 5, image: '/assets/img/Portfolio/Portfolio image-5.jpg', title: 'Shark', category: 'Waterbottle', description: 'A description of our service...'},
        { id: 6, image: '/assets/img/Portfolio/Portfolio image-6.jpg', title: 'Butterfly', category: 'Waterbottle', description: 'A description of our service...'},
        { id: 7, image: '/assets/img/Portfolio/Portfolio image-7.jpg', title: 'Snack Jar', category: 'Waterbottle', description: 'A description of our service...'},
        { id: 8, image: '/assets/img/Portfolio/Portfolio image-8.jpg', title: 'SF Keyring', category: 'Keyring', description: 'A description of our service...'},
        { id: 9, image: '/assets/img/Portfolio/Portfolio image-9.jpg', title: 'SF Keyring', category: 'Keyring', description: 'A description of our service...'},
        { id: 10, image: '/assets/img/Portfolio/Portfolio image-10.jpg', title: 'Hollywood Ornament Box', category: 'Ornament', description: 'A description of our service...'},
        { id: 11, image: '/assets/img/Portfolio/Portfolio image-11.jpg', title: 'Las Vegas Ornament Box', category: 'Ornament', description: 'A description of our service...'},
        { id: 12, image: '/assets/img/Portfolio/Portfolio image-12.jpg', title: 'Las Vegas Ornament Box', category: 'Ornament', description: 'A description of our service...'},
        { id: 13, image: '/assets/img/Portfolio/Portfolio image-13.jpg', title: 'New York Ornament Box', category: 'Ornament', description: 'A description of our service...'},
        { id: 14, image: '/assets/img/Portfolio/Portfolio image-14.jpg', title: 'Easter', category: 'Waterbottle', description: 'A description of our service...'},
        { id: 15, image: '/assets/img/Portfolio/Portfolio image-15.jpg', title: 'Camo', category: 'Waterbottle', description: 'A description of our service...'},
        { id: 16, image: '/assets/img/Portfolio/Portfolio image-16.jpg', title: 'Rainbow', category: 'Waterbottle', description: 'A description of our service...'},
        { id: 17, image: '/assets/img/Portfolio/Portfolio image-17.jpg', title: 'Swimming Lanes', category: 'Water', description: 'A description of our service...'},
        { id: 18, image: '/assets/img/Portfolio/Portfolio image-18.jpg', title: 'Swimming Lanes', category: 'Water', description: 'A description of our service...'},
        { id: 19, image: '/assets/img/Portfolio/Portfolio image-19.jpg', title: 'Swimming Lanes', category: 'Water', description: 'A description of our service...'},
        { id: 20, image: '/assets/img/Portfolio/Portfolio image-20.jpg', title: 'Swimming Lanes', category: 'Water', description: 'A description of our service...'},
        { id: 21, image: '/assets/img/Portfolio/Portfolio image-21.jpg', title: 'Swimming Lanes', category: 'Water', description: 'A description of our service...'},
        { id: 22, image: '/assets/img/Portfolio/Portfolio image-22.jpg', title: 'Swimming Lanes', category: 'Water', description: 'A description of our service...'},

    ],
}